export const books = [
  {
    slug: 'rifters-starfish',
    title: '海星',
    subtitle: 'Starfish',
    author: 'Peter Watts',
    description: '在太平洋海底的裂隙深处，一群被社会遗弃的人被改造成深海工人。他们发现自己比想象中更适应这个黑暗世界……',
    series: 'Rifters',
    seriesIndex: 1,
    year: 1999,
    date: '2026-02-25',
    status: 'coming-soon',
    tags: ['Science Fiction', '硬科幻', '深海'],
  },
  {
    slug: 'rifters-maelstrom',
    title: '漩涡',
    subtitle: 'Maelstrom',
    author: 'Peter Watts',
    description: '一种能吞噬生物圈的微生物正在蔓延。一个从深海归来的女人成了传说。世界在崩溃的边缘摇摇欲坠……',
    series: 'Rifters',
    seriesIndex: 2,
    year: 2001,
    date: '2026-02-25',
    status: 'available',
    tags: ['Science Fiction', '硬科幻', '网络'],
    htmlPath: '/books/rifters/maelstrom.html',
  },
  {
    slug: 'rifters-behemoth',
    title: 'βehemoth',
    subtitle: 'βehemoth',
    author: 'Peter Watts',
    description: '贝希摩斯已经不可遏制。在末日的最后阶段，幸存者们面对的不仅是一个垂死的世界，还有彼此……',
    series: 'Rifters',
    seriesIndex: 3,
    year: 2004,
    date: '2026-02-25',
    status: 'coming-soon',
    tags: ['Science Fiction', '硬科幻', '末日'],
  },
];
