export const reports = [
  {
    slug: '2026-04-cosco-shipping-energy',
    title: '中远海能 H 股 (1138.HK) 深度投研 v3.1',
    description: '霍尔木兹危机下的 VLCC 结构性牛市分析: 可比估值、红队测试、交易指引, 含 VLCC 订单与船价比值的实时监控仪表盘。',
    date: '2026-04-11',
    type: 'visualization',
    tags: ['投资分析', '航运', 'VLCC', 'LNG', '地缘政治'],
    component: () => import('./2026-04-cosco-shipping-energy/index.jsx'),
  },
  {
    slug: '2026-02-optical-communications',
    title: '光通信：AI数据中心的物理边界',
    description: 'Morgan Stanley研报摘要：光通信从升级周期到架构迁移，五条增量赛道TAM估算，OCS/CPO技术解读，个股估值与关键争论。',
    date: '2026-02-24',
    type: 'visualization',
    tags: ['投资分析', 'Optical', 'AI Infrastructure', '光通信', 'CPO', 'OCS'],
    component: () => import('./2026-02-optical-communications/index.jsx'),
  },
  {
    slug: '2026-02-solar-system',
    title: '3D Solar System Simulator',
    description: '交互式3D太阳系模拟器，支持手势控制',
    date: '2026-02-04',
    type: 'visualization',
    tags: ['3D', 'WebGL', 'Interactive', 'Space'],
    component: () => import('./2026-02-solar-system/index.jsx'),
  },
  {
    slug: '2026-02-zijin-mining',
    title: '紫金矿业深度分析',
    description: '紫金矿业 (2899.HK / 601899.SS) 投研分析：全球铜金龙头，AI时代的"新石油"供应商，央行购金浪潮的核心受益者。',
    date: '2026-02-03',
    type: 'visualization',
    tags: ['投资分析', 'Mining', 'Commodities', '铜', '黄金'],
    component: () => import('./2026-02-zijin-mining/index.jsx'),
  },
  {
    slug: '2025-01-enigma-of-reason',
    title: 'The Enigma of Reason',
    description: 'Interactive book report on "The Enigma of Reason" by Hugo Mercier & Dan Sperber — exploring the argumentative theory of reasoning.',
    date: '2025-02-01',
    type: 'visualization',
    tags: ['Cognitive Science', 'Psychology', 'Book Report'],
    component: () => import('./2025-01-enigma-of-reason/index.jsx'),
  },
  {
    slug: '2025-01-metals',
    title: 'Metals Commodity Prices (1975-2025)',
    description: '50-year historical data analysis of 8 major metals including gold, silver, copper, and more.',
    date: '2025-01-22',
    type: 'visualization',
    tags: ['Commodities', 'Metals', 'Data Visualization'],
    component: () => import('./2025-01-metals/index.jsx'),
  },
];
